### ISSUE TITLE
Option to empty the storage before upload ?

### ISSUE THREAD

**Issue by 0gust1** [tibor19/static-website-deploy#2]
Hi,

Thanks for this GH Action !

Is there an option to empty the storage before upload ?
I use this action to deploy the result of a VueJS build. Every important resulting assets names (JS and CSS files) are fingerprinted, and build after build, the Storage content is filling up.

**Comment by tibor19** [comment]
That is a good idea! If you have any code suggestions, please create a pull request for it.

**Comment by 0gust1** [comment]
OK. I took a look to the code.

Seems there is maybe an option for that, no ? 
https://github.com/tibor19/static-website-deploy/blob/e937952c714a3751355a17896498418a9931ded5/index.js#L56

**Comment by tibor19** [comment]
You are completely right. I forgot about it! :) 
``` remove-existing-files: true  ```
will do the trick.
