### ISSUE TITLE
Publish to a folder?

### ISSUE THREAD

**Issue by svrooij** [tibor19/static-website-deploy#6]
Would I be able to publish to a specific folder?

The use case is as follows. I run multiple open-source projects that are al documented at GitHub pages, but that doesn't allow me to publish the beta branch documentation.

Also PR requests that change the documentation should also be visible somewhere.

What I want to do is build the documentation and publish it to the storage account in the folder with the name of the branch. So storage.azurestorage.com/branch-name/index.html
That would make it easy to link to the beta docs or to publish some pr documentation.

**Comment by tibor19** [comment]
Short answer YES!

**Comment by svrooij** [comment]
This wasn't possible when I created the issue right?
I see the option in the readme now!
